-- MSSQL

-- Q1
	SELECT c.NAME
		 , MAX(o.ORDER_DATE) ORDER_DATE
	  FROM CUSTOMERS c
	 INNER JOIN ORDERS o  
	    ON c.CUSTOMER_ID = o.CUSTOMER_ID
	 GROUP BY c.NAME;

-- Q2
	  WITH RESULT AS (
	SELECT NAME, ORDER_DATE, CHANGE, ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY ABS(CHANGE) DESC) RNK
	  FROM (SELECT c.NAME
	  	 , o.ORDER_DATE
	  	 , SUM(QUANTITY) - LAG(SUM(QUANTITY),1) OVER (PARTITION BY NAME ORDER BY ORDER_DATE) AS CHANGE
	  FROM CUSTOMERS c
	 INNER JOIN ORDERS o 
	    ON c.CUSTOMER_ID = o.CUSTOMER_ID
	 WHERE o.QUANTITY <> 0
	 GROUP BY c.NAME
	 	 , o.ORDER_DATE) T
	 WHERE CHANGE IS NOT NULL)
	SELECT NAME, ORDER_DATE, CHANGE FROM RESULT WHERE RNK = 1